# Generated by Django 2.1.3 on 2019-10-06 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_profile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='bio',
            field=models.TextField(default='Just a new user . Add your bio'),
        ),
    ]
