# Generated by Django 2.1.11 on 2020-06-16 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_auto_20200615_1503'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='Profession',
            field=models.CharField(default='', max_length=20),
        ),
    ]
