# Generated by Django 2.1.11 on 2020-06-15 09:23

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0015_auto_20200614_1752'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='date_posted',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 15, 9, 23, 7, 849704, tzinfo=utc)),
        ),
    ]
