# Generated by Django 2.1.11 on 2020-06-16 07:39

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0020_auto_20200615_1747'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='date_posted',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 16, 7, 39, 8, 236116, tzinfo=utc)),
        ),
    ]
