# Generated by Django 2.1.11 on 2020-06-16 12:06

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0021_auto_20200616_1309'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='date_posted',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 16, 12, 6, 41, 642299, tzinfo=utc)),
        ),
    ]
