# Generated by Django 2.1.11 on 2020-06-16 12:09

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0022_auto_20200616_1736'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='date_posted',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 16, 12, 9, 18, 477650, tzinfo=utc)),
        ),
    ]
