# Generated by Django 2.1.11 on 2020-06-17 07:15

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0024_auto_20200617_1142'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='date_posted',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 17, 7, 15, 11, 413381, tzinfo=utc)),
        ),
    ]
