# Generated by Django 2.1.11 on 2020-06-17 09:54

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0025_auto_20200617_1245'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='date_posted',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 17, 9, 54, 24, 385608, tzinfo=utc)),
        ),
    ]
