# Generated by Django 2.1.11 on 2020-06-18 08:30

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0026_auto_20200617_1524'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='date_posted',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 18, 8, 30, 5, 309771, tzinfo=utc)),
        ),
    ]
